# Project-wide Gradle settings

# Enable parallel builds
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

# Kotlin
kotlin.code.style=official
kotlin.jvm.target=17
